### PR TITLE
[AVR] InstPrinter: Pretty print register names

### PR DESCRIPTION
**Pull request by agnat**
_Boom._

### CODE REVIEW

**Comment by Sh4rK** [comment]
I wanted to do some of this, but you're just too fast :D

**Comment by agnat** [comment]
Hm, CI complains... but it works for me. Let's have a look...

@Sh4rK: Hehe, sorry 'bout that.

**Comment by dylanmckay** [comment]
I checked out your changes manually on the command line and merged, and all passes tested.

Again, nice work :)

It looks like the backend is coming along, I have just fixed the encoding for the `LDD`/`STD` instructions, and now the MC test suite passes completely.

**Comment by dylanmckay** [comment]
For some reason the tests are failing on travis, but not on my computer. I have modified the travis script to run the tests verbosely, so we can see what the problem is.

**Comment by agnat** [comment]
Hm, I think travis is right. I get the same (totally obvious) errors after a clean rebuild. There are still old register names around.

Give me second. I'll do another PR

**Comment by dylanmckay** [comment]
I have a feeling that the reasons the tests were passing for me is because I was rebuilding only `llvm-mc`, even though the CodeGen tests use `llc`.

**Comment by dylanmckay** [comment]
`add.ll`:

```
/home/dylan/projects/avr-llvm/llvm/test/CodeGen/AVR/add.ll:35:10: error: expected string not found in input
; CHECK: adiw r25:r24, 63
         ^
<stdin>:47:16: note: scanning from here
add16_reg_imm: ; @add16_reg_imm
               ^
<stdin>:49:2: note: possible intended match here
 adiw r24, 63
 ^
```

**Comment by agnat** [comment]
Hehe... same here. Still learning how to ... drive this thing.

For reference:

https://github.com/avr-llvm/llvm/blob/avr-support/test/CodeGen/AVR/add.ll#L35

**Pull request merged**
