### PR TITLE
Experimental: Better inline asm

### PR DESCRIPTION
**Pull request by agnat**
This is work in progress.

I started looking into inline assembly. I'm currently stuck at this test case from CodeGen/AVR/inline-asm.ll:

``` asm
; RUN: llc < %s -march=avr | FileCheck %s

; CHECK-LABEL: multibyte_i32
define void @multibyte_i32(i32 %a) {
entry:
; CHECK: instr r22 r23 r24 r25
  call void asm sideeffect "instr ${0:A} ${0:B} ${0:C} ${0:D}", "r"(i32 %a)
; CHECK: instr r25 r24 r23 r22
  call void asm sideeffect "instr ${0:D} ${0:C} ${0:B} ${0:A}", "r"(i32 %a)
  ret void
}
````

Seems like handling of i32 values is missing. I've seen a few comments along the line "We only support i8 and i16". Why is that? Could you elaborate?

### CODE REVIEW

**Comment by dylanmckay** [comment]
I'm not really sure what you mean by "i32 support is missing?" - it is missing from what? Inline assembly? Instruction selection?

**Comment by agnat** [comment]
> [...]  it is missing from what?

Hehe... that's exactly what I'm trying to find out. The [case at hand](https://github.com/avr-llvm/llvm/blob/avr-support/lib/Target/AVR/AVRISelLowering.cpp#L1669-L1672) is related to inline assembly. But I believe I've seen comments and asserts to the same effect more than once. Other parts obviously do support larger types (artithmetic &c.). I guess my question is: Is it "not supported yet" or is it "here be dragons – not supported".

Since you weren't like "We decided to ignore >i16 because...", I guess it's just not implemented, right?

BTW, did you look at the patch? What do you think? Not worth the effort? To much mumbo-jumbo? I'm not sure yet...

**Comment by dylanmckay** [comment]
The patch looks like a simplification of the code to make it less verbose - that is always a win.

I have a feeling that the case you mention isn't suggesting that i32 support should be added - it is simply saying that these are the only possible options (there are no AVR instructions which take >16bit operands). There are only 8 and 16 bit register classes, so the function at hand couldn't use any other value types.

The only other place in the code that mentions "missing 32/16 bit support" that I can think of is `AVRInstrInfo.td`. In this case, it means that we are missing 16-bit (pseudo) variants of some instructions, so we cannot perform ISel on them, leading to instruction selection errors (pattern not resolved), or we miss an optimisation.

**Comment by agnat** [comment]
> There are only 8 and 16 bit register classes [...]

I think that is part of the problem. Looking at the test above and looking at what ARM does, it seems we need a quad pseudo register class. Let me look into it...

**Comment by dylanmckay** [comment]
If we need to define 16, 32, (and possibly 64) bit ISel patterns, we really need to come up with  a way to clean up `AVRExpandPseudoInsts.cpp`, as it is already at 1000+ lines of code, which is mostly repeated code.

**Comment by agnat** [comment]
I don't think we have to define additional patterns. Maybe load and store... at least not for the inline assembler.

I think we're on the same page. I don't want to add more pseudos let alone a whole set of them. I'm always looking for opportunities to offload work to ... existing infrastructure. ;)

Regarding `AVRExpandPseudoInsts.cpp`, I noticed the pattern. Pretty sure we can DRY that up. However, I think we should do #107 first... and yes that is a lot of work as it is.

**Comment by dylanmckay** [comment]
I am not much help when it comes to pseudo instructions, but only because I don't understand the live variables (I think) algorithm. Registers are marked as killed or dead in `AVRExpandPseudoInsts.cpp`, and I don't really know what's going on.

**Comment by agnat** [comment]
lol ... same here. Seems like quite a massacre.

But: We're going to find out. ;)

Fortunately, we don't have to grok the whole [register allocation algorithm](http://blog.llvm.org/2011/09/greedy-register-allocation-in-llvm-30.html). We just have to learn how to properly use it's API.

I think the main issue with `AVRExpandPseudoInsts.cpp` is: It does everything by index, which seems very error prone. I think I've read something about "named operand access", which sounds promising in this regard. Another thing to look into, though...

**Comment by agnat** [comment]
So...

This adds sub register access for i32 values, as in:

````
  call void asm sideeffect "instr ${0:A} ${0:B} ${0:C} ${0:D}", "r"(i32 %a)
````

However, I believe there must be a better way to achieve the same. I found this comment in [ARMDAGToDAGISel::SelectInlineAsm](https://github.com/avr-llvm/llvm/blob/avr-support/lib/Target/ARM/ARMISelDAGToDAG.cpp#L3767):

> Normally, i64 data is bounded to two arbitrary GRPs for "%r" constraint.
> However, some instrstions (e.g. ldrexd/strexd in ARM mode) require
> (even/even+1) GPRs and use %n and %Hn to refer to the individual regs
> respectively. Since there is no constraint to explicitly specify a
> reg pair, we use GPRPair reg class for "%r" for 64-bit data. For Thumb,
> the 64-bit data may be referred by H, Q, R modifiers, so we still pack
> them into a GPRPair.

We want what they describe as normality: Four arbitrary GPRs containing our i32 (I think it's called "expansion").

Also, note that the current implementation has bugs around [here](https://github.com/avr-llvm/llvm/blob/feature/better_inline_asm/lib/Target/AVR/AVRISelDAGToDAG.cpp#L430-L437)... and [there](https://github.com/avr-llvm/llvm/blob/feature/better_inline_asm/lib/Target/AVR/AVRISelDAGToDAG.cpp#L450-L454). I'll probably let it rest for a while and revisit it when I have a better understanding of the SelectionDAG.

Still experimental. Do not merge. ;)

**Comment by agnat** [comment]
OT: I somehow have the feeling `AVRExpandPseudoInsts.cpp` is not the way to go. It feels all wrong. Specially those instructions that just perform the same op on the low and the high part raise an eyebrow. I think non of this should be necessary.

**Pull request closed without merging**
