### PR TITLE
[AVR] fix load/store tests

### LINKED ISSUE #27: Fix CodeGen unit tests
Upon forking the original AVR-LLVM repository, a set of AVR tests were imported in the process.

They currently do not pass, and so they need to be fixed.

All of the imported tests exist in `test/CodeGen/AVR`.

Here are the tests:
- [x] add.ll
- [x] alloca.ll
- [x] and.ll
- [x] brind.ll
- [x] call.ll
- [x] cmp.ll
- [x] com.ll
- [x] directmem.ll
- [x] dynalloca.ll
- [x] frame.ll
- [ ] inline-asm.ll
- [x] interrupts.ll
- [x] io.ll
- [ ] load.ll
- [x] mul.ll
- [x] neg.ll
- [x] or.ll
- [ ] progmem.ll
- [x] return.ll
- [x] sext.ll
- [ ] store.ll
- [x] sub.ll
- [x] trunc.ll
- [x] varargs.ll
- [x] xor.ll
- [x] zext.ll

### PR DESCRIPTION
**Pull request by rjordans**
Partially fixes #27 by updating load/store tests to match with currently generated output.

### CODE REVIEW

**Comment by dylanmckay** [comment]
Are these registers consistent with the AVR C [calling convention](https://gcc.gnu.org/wiki/avr-gcc#Calling_Convention)?

**Comment by rjordans** [comment]
I think they are but I'll double check.  I did already spot one problem with my widened tests, the ldd operation is apparently only available for the Y and Z registers so that should be reflected in the tests.  Otherwise it looks OK I think, most tests don't actually check on the calling convention here anyway.  I'll check the calling convention correctness and store tests tomorrow.

**Comment by dylanmckay** [comment]
Once you check, tell me and I'd be happy to merge :)

Nice work!

**Comment by rjordans** [comment]
Hi Dylan,

Sorry for the long delay but I checked the tests now.  I've removed the X register from the option list for the load/store with displacement checks as those operations don't exist in the AVR architecture.  

Besides that everything seems to be OK now on my system.

Cheers,
 Roel

**Comment by rjordans** [comment]
Oh, and I've also checked the calling convention which seems to be consistent as well.  Some of the address registers do get moved from the input argument into other registers which was why the tests were failing.  These new tests don't check for the added moves and will assume that the calling convention is checked elsewhere.

**Comment by dylanmckay** [comment]
Nice work @rjordans, merging now :)

**Pull request merged**
