### PR TITLE
WIP: Use the generic branch relaxation infrastructure

### LINKED ISSUE #228: Use the generic branch relaxation infrastructure
I opened up a [patch](https://reviews.llvm.org/D25274) for the AVR branch selection pass. Matt Arsenault suggested we use the recently-added generic branch relation pass.

We should modify the code to use that and then push the patch back upstream.

An example can be found in the original implementation [here](https://reviews.llvm.org/D23271).

### PR DESCRIPTION
**Pull request by dylanmckay**
Fixes #228.

### CODE REVIEW

**Comment by shepmaster** [comment]
Exciting!

**Comment by dylanmckay** [comment]
Thinking about this more, we probably don't really need this.

It's true that in general, we definitely need some sort of branch relaxation as many of our instructions can only point ~127 bytes ahead or behind of the current IP, but this is normally done in the linker.

The backend used to resolve a lot more fixups to addresses, but I've changed that previously so that we almost always emit relocations in these cases. This means that the linker can do the relaxation.

**Comment by dylanmckay** [comment]
I've done this and it's in LLVM trunk.

**Comment by shepmaster** [comment]
Should we delete the branch or do you want to keep it for posterity?

**Comment by dylanmckay** [comment]
Might as well delete to be honest, this patch only has a small amount of the actual code required/

**Pull request closed without merging**
