### PR TITLE
Merge in LLVM 3.9 release branch

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by shepmaster** [comment]
@dylanmckay Probably the thing you need to review most is my nasty hacks to get it to merge...

**Comment by shepmaster** [comment]
Ugh. Travis doesn't have an easy way to install CMake 3.4+

**Comment by shepmaster** [comment]
In case it gets lost in the large amount of commits, I'm also changing how we get CMake in Travis and disabling Clang / compiler-rt again (as they need to be updated)

**Comment by dylanmckay** [comment]
Go fourth and merge!

**Comment by shepmaster** [comment]
Alrighty then.

**Pull request merged**
