### PR TITLE
More GCC compatibility quirks

### PR DESCRIPTION
**Pull request by agnat**
Add handling of numeric register names.

### CODE REVIEW

**Comment by dylanmckay** [comment]
Looks good but do we really want to conditionally support GCC based on a preprocessor define? Is there any reason that it'd ever be disabled?

Nice work on all of the AsmParser improvements btw, it was in serious need of refactoring.

**Comment by agnat** [comment]
> [...] do we really want to conditionally support GCC based on a preprocessor define?

The define is just the cheapest way to tag the relevant sections, so they don't get lost. In the long run I'd like to add a command line option to disable the GCC quirks.

>  Is there any reason that it'd ever be disabled?

Yes. Better diagnostics. Things like numeric register names, optional comma and the like add ambiguity. Suddenly almost everything is valid input. Silently generating "not what the user wants" becomes much more likely. This kind of "misunderstanding" is the worst kind of error: A simple typo, zero diagnostics and completely bizarre behavior (a backend crash at best).

Considering that the AVR has become the No.1 education platform (for this sort of thing) and that LLVM is supposed to be the "understandable toolchain" adding a strict mode feels like the right thing to do.

However, non of this has be done right now. Keeping the code separate (by some means) just leaves us the option. 
 
> Nice work on all of the AsmParser improvements btw, 

Thanks.

> it was in serious need of refactoring.

Yes.

**Comment by dylanmckay** [comment]
I agree :) Rollup and I'll merge.

**Comment by agnat** [comment]
Done.

**Pull request merged**
