### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by RandomInsano**
Runs the 111 tests available.

Needs commit squashing.

### CODE REVIEW

**Comment by RandomInsano** [comment]
Should fix #42

**Comment by RandomInsano** [comment]
Looks broken. Moment.

**Comment by dylanmckay** [comment]
Once the commits are squashed, I'll merge :)

**Comment by RandomInsano** [comment]
Touché! I'll try and get that done tomorrow evening.

**Comment by dylanmckay** [comment]
I squashed the commits and committed them in 9f1f4ea6f0da68b7f9ecbb545ef8ae513bbca563.

**Pull request closed without merging**
