### PR TITLE
Fix broken build.

### PR DESCRIPTION
**Pull request by saaadhu**
I know you're in the process of getting the code into the LLVM backend, so I don't know how useful this is. I tried building this on a Windows machine and had to fix these to get the build going.

### CODE REVIEW

**Comment by dylanmckay** [comment]
I haven't started the merge for these files yet so this is good!

Thanks for saving the Windows users :)

**Comment by DavidEGrayson** [comment]
if (AVR::isProgramMemoryAddress(GV) and not GV->hasSection())

That looks more like Python than C++.  How was that code successfully compiled before?  Is there some C++ extension to support "and" and "not" operators?

**Comment by saaadhu** [comment]
I thought that was the case too, until I googled and saw this -
http://stackoverflow.com/questions/1433345/or-is-not-valid-c-why-does-this-code-compile/1433352#1433352

**Comment by agnat** [comment]
> How was that code successfully compiled before?

AFAIK, it is standard C++ and they are called  "operator synonyms"...

**Comment by agnat** [comment]
Oh... what @saaadhu says. The standard has them as **2.6 Alternative tokens [lex.digraph]**.

**Pull request merged**
